/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.28
 * Generated at: 2018-07-02 15:49:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import com.example.New_Employees_Connection;

public final class New_005fEmployees_005fTable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.example.New_Employees_Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t\r\n");
      out.write("<title>Employee Info</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/New_Employees_Design.css\" type=\"text/css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		String print = request.getParameter("yes_to_print");
		if (print != null && print.toString().equalsIgnoreCase("YES")) {
			response.setContentType("application/vnd.excel");
			response.setHeader("Content-Disposition", "inline; filename=My_Employee_Info.pdf");
		}
	
      out.write("\r\n");
      out.write("<H1>Employee Table and Information</H1>\r\n");
      out.write("\r\n");

		if(session.getAttribute("user") == null)
			response.sendRedirect("Login.jsp");

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t");

 		New_Employees_Connection ts = new New_Employees_Connection();
		ResultSet rs = ts.getRS();
     
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <TABLE BORDER=\"1\">\r\n");
      out.write("            <TR>\r\n");
      out.write("                <TH>Employee ID</TH>\r\n");
      out.write("                <TH>Name</TH>\r\n");
      out.write("                <TH>Email</TH>\r\n");
      out.write("                <TH>SSN</TH>\r\n");
      out.write("                <TH>Last 4 SSN</TH>\r\n");
      out.write("                <TH>Encrypted SSN</TH>\r\n");
      out.write("            </TR>\r\n");
      out.write("            ");
 while(rs.next()){ 
      out.write("\r\n");
      out.write("            <TR>\r\n");
      out.write("                <TD> ");
      out.print( rs.getString(1) );
      out.write("</td>\r\n");
      out.write("                <TD> ");
      out.print( rs.getString(2) );
      out.write("</td>\r\n");
      out.write("                <TD> ");
      out.print( rs.getString(3) );
      out.write("</td>\r\n");
      out.write("                <TD> ");
      out.print( rs.getString(4) );
      out.write("</td>\r\n");
      out.write("                <TD> ");
      out.print( rs.getString(5) );
      out.write("</td>\r\n");
      out.write("                <TD> ");
      out.print( rs.getString(6) );
      out.write("</td>\r\n");
      out.write("            </TR>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </TABLE>\r\n");
      out.write("        <br/>\r\n");
      out.write("        <br/>\r\n");
      out.write("<button type=\"button\" onclick=\"location.href= '/Demo_Project/New_Employees_Form.jsp';\">New Employees Form</button>\r\n");
      out.write("<button type=\"button\" onclick=\"location.href= '/Demo_Project/myJsp.jsp';\">Main Menu</button>\r\n");
      out.write("<a href=\"New_Employees_Table.jsp?yes_to_print=YES\"><button>Print Table</button></a>\r\n");
      out.write("<br/>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
