/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.28
 * Generated at: 2018-07-02 15:49:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.example.New_Employees_Connection;
import java.sql.ResultSet;

public final class New_005fEmployees_005fForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.example.New_Employees_Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>New Employee Form</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

		if(session.getAttribute("user") == null)
			response.sendRedirect("Login.jsp");

      out.write("\r\n");
      out.write("\r\n");

	New_Employees_Connection ts = new New_Employees_Connection();
	ResultSet rs = ts.getRS();

      out.write("\r\n");
      out.write("<form method=\"post\" action=\"/Demo_Project/New_Employees_Form_Submit.jsp\">\r\n");
      out.write("First name:<br> <input type=\"text\" name=\"first_name\">\r\n");
      out.write("<br/>\r\n");
      out.write("Last name:<br> <input type=\"text\" name=\"last_name\">\r\n");
      out.write("<br/>\r\n");
      out.write("SSN:<br> <input type=\"text\" name=\"ssn\">\r\n");
      out.write("<br/>\r\n");
      out.write("Job ID:<br> <select name=\"job_id\">\r\n");
      out.write("\t\t  <option value=\"AD_PRES\">President</option>\r\n");
      out.write("\t\t  <option value=\"AD_VP\">Administration Vice President</option>\r\n");
      out.write("\t\t  <option value=\"AD_ASST\">Administration Assistant</option>\r\n");
      out.write("\t\t  <option value=\"FI_MGR\">Finance Manager</option>\r\n");
      out.write("\t\t  <option value=\"FI_ACCOUNT\">Accountant</option>\r\n");
      out.write("\t\t  <option value=\"AC_MGR\">Accounting Manager</option>\r\n");
      out.write("\t\t  <option value=\"AC_ACCOUNT\">Public Accountant</option>\r\n");
      out.write("\t\t  <option value=\"SA_MAN\">Sales Manager</option>\r\n");
      out.write("\t\t  <option value=\"SA_REP\">Sales Representative</option>\r\n");
      out.write("\t\t  <option value=\"PU_MAN\">Purchasing Manager</option>\r\n");
      out.write("\t\t  <option value=\"PU_CLERK\">Purchasing Clerk</option>\r\n");
      out.write("\t\t  <option value=\"ST_MAN\">Stock Manager</option>\r\n");
      out.write("\t\t  <option value=\"ST_CLERK\">Stock Clerk</option>\r\n");
      out.write("\t\t  <option value=\"SH_CLERK\">Shipping Clerk</option>\r\n");
      out.write("\t\t  <option value=\"IT_PROG\">Programmer</option>\r\n");
      out.write("\t\t  <option value=\"MK_MAN\">Marketing Manager</option>\r\n");
      out.write("\t\t  <option value=\"MK_REP\">Marketing Representative</option>\r\n");
      out.write("\t\t  <option value=\"HR_REP\">Human Resources Representative</option>\r\n");
      out.write("\t\t  <option value=\"PR_REP\">Public Relations Representative</option>\r\n");
      out.write(" </select>\r\n");
      out.write("<br/>\r\n");
      out.write("Manager Email: <br> <select name=\"manager\">\r\n");
      out.write("\t\t\t<option value =");
      out.print((String) session.getAttribute("id"));
      out.write('>');
      out.write(' ');
      out.print((String) session.getAttribute("user"));
      out.write("</option>\r\n");
      out.write("\t\t\t<option value = null> Not Applicable</option>\r\n");
      out.write("</select>\r\n");
      out.write("<br/>\r\n");
      out.write("Date: yyyy-mm-dd <br> <input type=\"date\" name=\"date_a\">\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("</form>\r\n");
      out.write("<button type=\"button\" onclick=\"location.href= '/Demo_Project/myJsp.jsp';\">Main Menu</button>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<button type=\"button\" onclick=\"location.href= '/Demo_Project/FormTest1.jsp';\">Practice Action</button>\r\n");
      out.write("<br/>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
